### ISSUE TITLE
Set up running instance of vivo-scholar populated with openvivo data

### ISSUE THREAD

**Issue by nymbyl** [vivo-community/scholars-discovery#105]
Need a public instance for SOLR and another for running the vivo-scholar project.  This is so anybody can hit the graphql endpoint. The plan is to house this in an Openshift environment at Duke

**Comment by ht29** [comment]
It is setup in Openshift.

Here is Openshift link:
https://vivo-scholars-scholars.cloud.duke.edu

Thanks,
-Harry
