### ISSUE TITLE
Tweaks for conference demo / early access preview

### ISSUE THREAD

**Issue by outten45** [vivo-community/scholars-discovery#137]
List of tweaks for the demo or early access preview that we want to deploy. See demo from the meeting this morning.
https://drive.google.com/drive/folders/1kFkmuozdKCr00MDWkCvXS7J5WeX_sHjL

- [x] full position information
- [x] add photo (Damaris)
- [ ] tabs to demo: About, Background, and Research & Expertise tabs (Damaris)
- [x] Remove "@en-US" with JavaScript
- [x] add space next to checkbox on search page
- [x] add padding to the left and right of the page
- [x] add more space to the top of the headings on the profile page
- [x] add padding above headings on the search page
- [x] switch to Red Hat Text (see https://docs.google.com/document/d/1yvC1g1p-egfOtGUMRyU6nR8HEpbRTcYTddzr9tzKyN8/edit)
- [x] create some sample graphql queries for talk

**Comment by nymbyl** [comment]
Put a few sample queries here:
https://github.com/vivo-community/scholars-discovery/wiki/Sample-GraphQL-queries

**Comment by nymbyl** [comment]
Made a vstf-demo branch for deployment to openshift (for now).
