### ISSUE TITLE
Prune top-level GraphQL queries

### ISSUE THREAD

**Issue by jimwood** [vivo-community/scholars-discovery#174]
Proposal: Limit top-level queries to simplify interface. Ideally this would be 2 per type. For example:

person -> Currently personById, this would work the same way (find 1 person using their identifier)
people -> Currently personFacetedSearch, this would change to implement defaults for any parameter not specified:
- empty facets
- empty filters
- default pagination (configurable)
- default sort
- return all results of no query

If that is not possible due to return types then people could be split into:
personSearch (as above but query is required)
personList (as above but no query parameter)

**Comment by wwelling** [comment]
Simply remove `@GraphQLQuery` annotations from methods you do not want exposed as resolvers and change the names of the resolvers you would like. May have to remove the argument annotations as well. If the function is not an override it can be removed.

**Comment by jimwood** [comment]
Determine core set of top-level queries from options above based on return type limitations

Remove overriding of methods in grapqhl.service classes that won't be used as resolvers. Update graphql resolver names in the annotations.

**Comment by bluedevelz** [comment]
A pull request for an implementation that should satisfy the requirements has been created.
