### ISSUE TITLE
Search: add ability to send facet.mincount as parameter

### ISSUE THREAD

**Issue by nymbyl** [vivo-community/scholars-discovery#219]

**Comment by wwelling** [comment]
You can provide pageNumbe and pageSize to the [FacetArg](https://github.com/vivo-community/scholars-discovery/blob/master/src/main/java/edu/tamu/scholars/middleware/discovery/argument/FacetArg.java) to paginate the facet entries.

Solr is limited on ability to paginate facet entries. It only offers mincount, therefor scholars-discovery gets all possible facet entries and provides pagination over them.

**Comment by wwelling** [comment]
Is the intent of this issue, to also afford on requesting mincount from Solr and not paginate them?

**Comment by nymbyl** [comment]
Sorry - just saw your comment.  What I was trying to do is allow showing facets with 0 counts - so that when filters are applied - and then other filters are applied that make those inapplicable - the original filters can still hang around as facets with 0 counts.  

So - yes - just the mincount - not paginating

**Comment by wwelling** [comment]
I apologize. You are right. These are not the same thing. Also, correction to above. It is Spring Data Solr that does not paginate facet entries properly as facet.offset and facet.limit is offered by Solr.
